### ISSUE TITLE
getting started newbie question

### ISSUE THREAD

**Issue by annoporci** [liquidpele/nvd3#44]
As a newbie I would suggest adding a little more detail to the README.md, in particular how to actually source the code from your repo, as opposed to the 'dead' master branch. Here is an example that explains what you have to include in the html: http://dimplejs.org/, you could similarly explain whether d3.v3.min.js and the like need/need not be included.

**Comment by RenatoUtsch** [comment]
Look here:
https://github.com/nvd3-community/nvd3

**Comment by annoporci** [comment]
Thanks Renato,
do you mean this part?

So I need grunt (whatever that is), correct? I thougth I could just copy a few of the relevant files into the right directories, sounds a bit complicated!

    **Building latest**

        First clone the repository and checkout the "development" branch
        make sure nodejs is installed via your system's package manager.
        have node download it's required modules with: npm install
        install grunt globally: sudo npm install -g grunt
        build with: grunt production

    You should now have a "build" directory with the js and css files within.

**Comment by liquidpele** [comment]
You can use the files in the "build" directory, those are already built.  Using grunt is required to build it yourself.  This project has been moved under the nvd3-community org at this point, which is why my personal fork here has the "dead" master branch.

**Comment by annoporci** [comment]
Thanks liquidpele good to know!
